version: '3.8'
services:
  waco-display-box:
    image: node:latest
    working_dir: /app
    ports:
      # Make sure to also update the CLI ENV VAR in package.json
      - "3201:3201"
    volumes:
      - ./src/:/app
      #- /app/node_modules
    env_file:
      - .env
    command: sh -c "npm install && npm start -- -H 0.0.0.0"