version: '3.8'
services:
  waco-display-box:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    env_file: .env
    restart: unless-stopped
  web:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"
    restart: unless-stopped